name: GrassGrow
main: io.github.BrainStone.GrassGrow.GrassGrow
version: 1.8.0
author: The_BrainStone

commands:
  grassgrow:
    description: Makes grass grow arround you
    usage: |
      /<command> [enable|en] <console only:player> [radius]
      /<command> [disable|dis] <console only:player>
    permission: grassgrow.grow
    permission-message: You don't have <permission>
    aliases: [gg, GG, g_g, G_G]
    
permissions:
  grassgrow.grow:
    descrition: Let's you use the grasgrow command
    default: false
  grassgrow.*:
    description: Gives you all grasgrow permissions
    children:
      grasgrow.grow: true